default: &default
  adapter: mysql2
  encoding: utf8mb4
  collate: utf8mb4_unicode_ci
  host: mysql
  port: 3306
  username: root
  password: password

development:
  <<: *default
  database: qconcursos_development

test:
  <<: *default
  database: qconcursos_test